- name: Install and Deploy the control server with its services
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  roles:
    - roles/init-env
    - roles/configure_tftpd
    - roles/configure_apache2
    - roles/configure_firewalld
  ### note, the configure_apparmor task must be executed before bind9, and isc-dhcp to give both process permission to access config files located in /acpc/adm/etc
    - roles/configure_apparmor
    - roles/configure_bind
    - roles/configure_dhcpd
    - roles/configure_perl
    - roles/configure_nodeexporter
