---
# tasks file for roles/configure_perl
- name: Extract perl modules 
  unarchive:
    src: "{{item}}"
    dest: "/tmp"
  with_items:
    - "files/acpc/PDF-Create-1.46.tar.gz"
    - "files/acpc/File-ShareDir-Install-0.13.tar.gz"
    - "files/acpc/JSON-4.02.tar.gz"
    - "files/acpc/Class-Inspector-1.36.tar.gz"
    - "files/acpc/File-ShareDir-1.116.tar.gz"
    - "files/acpc/File-Share-0.25.tar.gz"

- name: Configure and install perl modules
  shell: "cd {{item}} && perl Makefile.PL && make && make install"
  with_items:
    - "/tmp/Class-Inspector-1.36"
    - "/tmp/File-ShareDir-1.116"
    - "/tmp/File-Share-0.25"
    - "/tmp/File-ShareDir-Install-0.13"
    - "/tmp/PDF-Create-1.46"
    - "/tmp/JSON-4.02"



