---
# tasks file for roles/configure_dhcpd
#- name: Change ownership of /acpc/adm/etc/dhcp/
#ansible.builtin.file:
#path: /acpc/adm/etc/dhcp/
#state: directory
#recurse: yes
#owner: dhcpd
#group: dhcpd

- name: Copy dhcpd.conf file
  copy:
    src: files/acpc/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
  notify: Restart DHCP
