    - name: add hostname to hosts file
      lineinfile:
       dest: /etc/hosts
       line: "127.0.0.1 acpccontrol"
       state: present

    - name: set the hostname
      hostname:
       name: acpccontrol

    - name: Create /acpc tree
      file:
              path: "/{{item}}"
              state: directory
              mode: 0755
      with_items: ["acpc","/MirrorPool"]

    - name: Install basic packages needed
      apt:
              name: ["apache2","bind9","isc-dhcp-server","tftpd-hpa","git","python3-pip","make","gcc","libnm-glib-dev","network-manager","firewalld"]
              update_cache: yes

    - name: Deploy to /acpc/adm
      git:
          repo: '{{ACPC_GITHUP}}/acpc-control-adm'
          dest: /acpc/adm

    - name: Deploy to /var/lib/tftpboot
      git:
              repo: '{{ACPC_GITHUP}}/acpc-control-tftpd'
              dest: /var/lib/tftpboot

    - name: Deploy to /acpc/progs
      git:
              repo: '{{ACPC_GITHUP}}/acpc-control-prog'
              dest: /acpc/progs

    - name: Update apache2 config
      lineinfile:
              dest: /etc/apache2/apache2.conf
              line: "Include /acpc/adm/etc/apache2/server.conf"
              state: present
      notify: Apache2 config changed

    - name: Update Apache2 default site
      lineinfile:
              dest: /etc/apache2/sites-enabled/000-default.conf
              line: "Include /acpc/adm/etc/apache2/acpc.conf"
              state: present
      notify: Apache2 config changed

    - apache2_module:
       state: present
       name: cgid
      notify: Apache2 config changed

    - name: Update BIND9 configuration files named.conf
      lineinfile:
              dest: /etc/bind/named.conf
              line: "include \"/acpc/adm/etc/bind/acls.conf\";"
              state: present
      notify: BIND9 config changed


    - name: Update BIND9 configuration files named.conf.default-zones
      lineinfile:
              dest: /etc/bind/named.conf.default-zones
              line: "{{ item }}"
              state: present
      with_items: 
              - "include \"/acpc/adm/etc/bind/acpcDomain.conf\";"
              - "include \"/acpc/adm/etc/bind/acpcReverseDomain.conf\";"
      notify: BIND9 config changed

    - name: Update BIND9 configuration files named.conf.options
      lineinfile:
              dest: /etc/bind/named.conf.options
              line: "include \"/acpc/adm/etc/bind/dhcpupdate.conf\";"
              state: present
      notify: BIND9 config changed

    - name: Copying empty template for forward resolv
      copy:
              src: /etc/bind/db.empty
              dest: /var/lib/bind/aecpc.eg
              remote_src: yes
              owner: bind
              group: bind
      notify: BIND9 config changed

    - name: Copying empty template for reverse resolv
      copy:
              src: /etc/bind/db.0
              dest: /var/lib/bind/16.20.172.in-addr.arpa
              remote_src: yes
              owner: bind
              group: bind
      notify: BIND9 config changed

    - name: Copy dhcpd.conf file
      copy:
              src: acpc/dhcpd.conf
              dest: /etc/dhcp/dhcpd.conf
      notify: ISC-DHCP config changed

    - name: Allow bind-dhcp dynamic update to write to dirs with named
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.named
        line: "{{item}}"
        state: present
        insertbefore: "}"
      with_items: 
        - "/acpc/adm/etc/bind/dhcpupdate.conf r,"
        - "/acpc/adm/etc/bind/acpcDomain.conf r,"
        - "/acpc/adm/etc/bind/acpcReverseDomain.conf r,"
        - "/acpc/adm/etc/bind/acls.conf r,"
      notify: 
        - Apparmor config changed
        - BIND9 config changed
    
    - name: Allow bind-dhcp dynamic update to write to dirs with dhcpd
      lineinfile:
        path: /etc/apparmor.d/usr.sbin.dhcpd
        line: "{{item}}"
        state: present
        insertbefore: "}"
      with_items:
        - "/acpc/adm/etc/dhcp/dhcpd.conf.options r,"
        - "/acpc/adm/etc/bind/dhcpupdate.conf r,"
        - "/acpc/adm/etc/dhcp/dhcpd.conf.subnet r,"
        - "/acpc/adm/etc/dhcp/dhcpd.conf.hosts r,"
        - "/acpc/adm/etc/dhcp/domainupdate r,"
        - "/acpc/adm/etc/dhcp/reversedomainupdate r,"
        - "/acpc/adm/etc/dhcp/dhcpupdate.conf r,"
      notify:
        - Apparmor config changed
        - ISC-DHCP config changed

    - name: Disable ssh HostKeyChecking
      replace:
             path: /etc/ssh/ssh_config
             regexp: "#   StrictHostKeyChecking ask"
             replace: "StrictHostKeyChecking no"

    - name: Extract perl modules 
      unarchive:
        src: "{{item}}" 
        dest: "/tmp"
      with_items:
              - "acpc/PDF-Create-1.46.tar.gz"
              - "acpc/File-ShareDir-Install-0.13.tar.gz"
              - "acpc/JSON-4.02.tar.gz"
              - "acpc/Class-Inspector-1.36.tar.gz"
              - "acpc/File-ShareDir-1.116.tar.gz"
              - "acpc/File-Share-0.25.tar.gz"

    - name: Configure and install perl modules
      shell: "cd {{item}} && perl Makefile.PL && make && make install"
      with_items:
              - "/tmp/Class-Inspector-1.36"
              - "/tmp/File-ShareDir-1.116"
              - "/tmp/File-Share-0.25"
              - "/tmp/File-ShareDir-Install-0.13"
              - "/tmp/PDF-Create-1.46"
              - "/tmp/JSON-4.02"

    - name: Copy /etc/default/grub
      copy:
              src: acpc/grub
              dest: /etc/default/grub

    - name: Updating /boot/grub/grub.cfg 
      shell: "grub-mkconfig -o /boot/grub/grub.cfg"

    - name: Start Network-Manager
      service:
       name: network-manager
       state: started

    - name: create 10-globally-managed-devices.conf
      file:
              path: "/etc/NetworkManager/conf.d/10-globally-managed-devices.conf"
              state: touch

    - name: Configure an ethernet connection for eth0
      nmcli:
              conn_name: Internal
              ifname: eth0
              type: ethernet
              ip4: 172.20.16.2/24
              gw4: 172.20.16.5
              state: present
              autoconnect: yes

    - name: Starting firewalld
      service:
              name: firewalld
              state: started

    - name: Configuring firewalld rules
      firewalld:
              service: "{{item}}"
              permanent: yes
              state: enabled
      with_items:
              - "http"
              - "https"
              - "dns"
              - "dhcp"
              - "tftp"

