---
# tasks file for roles/configure_apache2
- name: Update apache2 config
  lineinfile:
    dest: /etc/apache2/apache2.conf
    line: "Include /acpc/adm/etc/apache2/server.conf"
    state: present
  notify: Restart apache2

- name: Update Apache2 default site
  lineinfile:
    dest: /etc/apache2/sites-enabled/000-default.conf
    line: "Include /acpc/adm/etc/apache2/acpc.conf"
    state: present
  notify: Restart apache2

    #### Use the url to configure mod-security
    #https://www.linode.com/docs/guides/securing-apache2-with-modsecurity/
    #https://www.inmotionhosting.com/support/server/apache/install-modsecurity-apache-module/
- name: Install required apache modules
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - cgid
    - rewrite
    - headers
  notify: Restart apache2

- name: Change ownership of /acpc/adm/etc/
  ansible.builtin.file:
    path: /acpc/adm/etc/
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
